name: "CI :: Integration Tests"

on: push

jobs:
  online-editor-tests-it:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [12.16.3]
        yarn: [1.19.1]

    steps:
      - uses: actions/checkout@v2
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Setup Yarn
        run: |
          npm install -g yarn@${{ matrix.yarn }}
          yarn config set network-timeout 1000000

      - name: Download dependencies
        run: yarn run init

      - name: Increase inotify watches
        if: matrix.os == 'ubuntu-latest'
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

      - name: Build repository
        run: npx lerna run build:prod --scope '@kogito-tooling/online-editor' --include-dependencies

      - name: Run integration tests
        run: npx lerna run test:it --scope '@kogito-tooling/online-editor' --stream

      - name: Archive it test screenshots	
        if: failure()
        uses: actions/upload-artifact@v1	
        with:	
          name: online-editor-it-tests-screenshots-${{ matrix.os }}	
          path: packages/online-editor/it-tests/screenshots

      - name: Archive it test videos	
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: online-editor-it-tests-videos-${{ matrix.os }}
          path: packages/online-editor/it-tests/videos
